export const parts = [
  {
    id: 1,
    parts: 'AC Compressor',
    category: 'AC parts',
    description: '',
    img: 'AC_Compressor.png',
  },
  {
    id: 2,
    parts: 'AC Condenser',
    category: 'AC parts',
    description: '',
    img: 'AC_Condenser.png',
  },
  {
    id: 3,
    parts: 'AC Condenser Cooling Fan',
    category: 'AC parts',
    description: '',
    img: 'AC_Condenser_Cooling_Fan.png',
  },
  {
    id: 4,
    parts: 'AC Controls',
    category: 'AC parts',
    description: '',
    img: 'AC_Controls.png',
  },
  {
    id: 5,
    parts: 'AC Evaporator',
    category: 'AC parts',
    description: '',
    img: '',
  },
  {
    id: 6,
    parts: 'AC Evaporator Housing',
    category: 'AC parts',
    description: '',
    img: '',
  },
  {
    id: 7,
    parts: 'AC Selector',
    category: 'AC parts',
    description: '',
    img: '',
  },
  {
    id: 8,
    parts: 'Air Bag Assembly',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 9,
    parts: 'Air Bag Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 10,
    parts: 'Air Bag Detector',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 11,
    parts: 'Air Cleaner Assembly',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 12,
    parts: 'Air Flow Meter',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 13,
    parts: 'Air Injection Pump',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 14,
    parts: 'Air Ride Compressor',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 15,
    parts: 'Air Ride Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 16,
    parts: 'Alternator',
    category: '',
    description:
      'Alternators for all vehicles are manufactured using Quality Standards and 100% end-of-line computerised.',
  },
  {
    id: 17,
    parts: 'Antenna (Electric)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 18,
    parts: 'Antenna (Manual)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 19,
    parts: 'Anti-Lock Brake Control Module (ABS)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 20,
    parts: 'Anti-Theft Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 21,
    parts: 'Axle Assembly (Front, 4WD)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 22,
    parts: 'Axle Assembly (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 23,
    parts: 'Axle Beam (Front, 2WD)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 24,
    parts: 'Axle Beam (Rear, FWD, Complete)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 25,
    parts: 'Axle Shaft',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 26,
    parts: 'Back Glass',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 27,
    parts: 'Backup Light',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 28,
    parts: 'Battery',
    category: '',
    description:
      'The Automobile Batteries are manufactured using the best quality raw materials that has a high power, performance and reliability.',
  },
  {
    id: 29,
    parts: 'Bed (Pickup)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 30,
    parts: 'Bell Housing',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 31,
    parts: 'Belt Tensioner',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 32,
    parts: 'Blower Motor',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 33,
    parts: 'Body Control Module (BCM)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 34,
    parts: 'Brake Booster',
    category: '',
    description:
      'Braking system from high end manufacturers using high quality metallic, carbon-based, brass bonded resins, steel and graphite in UAE.',
  },
  {
    id: 35,
    parts: 'Bumper Assembly (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 36,
    parts: 'Bumper Assembly (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 37,
    parts: 'Bumper Cover (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 38,
    parts: 'Bumper Cover (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 39,
    parts: 'Bumper Shock',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 40,
    parts: 'Cab Clip',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 41,
    parts: 'Caliper',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 42,
    parts: 'Camshaft',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 43,
    parts: 'Carburetor',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 44,
    parts: 'Carrier Assembly',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 45,
    parts: 'Cassette Player',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 46,
    parts: 'CD Changer',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 47,
    parts: 'CD Player',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 48,
    parts: 'Chassis Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 49,
    parts: 'Clock',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 50,
    parts: 'Coil (Ignition)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 51,
    parts: 'Coil Spring (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 52,
    parts: 'Coil Spring (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 53,
    parts: 'Column Shift Lever',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 54,
    parts: 'Column Switch',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 55,
    parts: 'Computer (ECU, ECM)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 56,
    parts: 'Console',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 57,
    parts: 'Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 58,
    parts: 'Convertible Top',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 59,
    parts: 'Convertible Top Motor',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 60,
    parts: 'Coolant Reservoir',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 61,
    parts: 'Cooling Fans Assembly (Rad. & Cond.)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 62,
    parts: 'Cornering Light',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 63,
    parts: 'Cowl',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 64,
    parts: 'Crankshaft',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 65,
    parts: 'Cruise Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 66,
    parts: 'Cylinder Block',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 67,
    parts: 'Cylinder Head',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 68,
    parts: 'Dashboard Assembly',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 69,
    parts: 'Dashboard Pad',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 70,
    parts: 'Decklid',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 71,
    parts: 'Decklid Pull Down Motor',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 72,
    parts: 'Differential Assembly (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 73,
    parts: 'Differential Assembly (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 74,
    parts: 'Differential Case',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 75,
    parts: 'Distributor',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 76,
    parts: 'Door Assembly (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 77,
    parts: 'Door Assembly (Rear or Back)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 78,
    parts: 'Door Glass (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 79,
    parts: 'Door Glass (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 80,
    parts: 'Door Handle (Inside)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 81,
    parts: 'Door Handle (Outside)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 82,
    parts: 'Door Lock Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 83,
    parts: 'Door Motor (Power Slider|Tailgate, Van)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 84,
    parts: 'Door Switch',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 85,
    parts: 'Door Vent Glass (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 86,
    parts: 'Door Vent Glass (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 87,
    parts: 'Door Vent Glass Regulator (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 88,
    parts: 'Door Window Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 89,
    parts: 'Door Window Motor (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 90,
    parts: 'Door Window Motor (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 91,
    parts: 'Door Window Regulator (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 92,
    parts: 'Door Window Regulator (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 93,
    parts: 'Drive Shaft (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 94,
    parts: 'Drive Shaft (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 951,
    parts: 'Driving Light',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 96,
    parts: 'Engine Assembly',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 97,
    parts: 'Engine Block',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 98,
    parts: 'Engine Control Module (ECU, ECM)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 99,
    parts: 'Engine Mount',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 100,
    parts: 'Engine Oil Cooler',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 101,
    parts: 'Engine Wiring Harness',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 102,
    parts: 'Exhaust Manifold',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 103,
    parts: 'Fan Blade',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 104,
    parts: 'Fan Clutch',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 105,
    parts: 'Fan Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 106,
    parts: 'Fender (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 107,
    parts: 'Fender (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 108,
    parts: 'Flywheel',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 109,
    parts: 'Fog Light',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 110,
    parts: 'Frame (Complete)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 111,
    parts: 'Frame (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 112,
    parts: 'Front End Assembly (Nose)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 113,
    parts: 'Fuel Door',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 114,
    parts: 'Fuel Injection Pump',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 115,
    parts: 'Fuel Pump',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 116,
    parts: 'Fuel Sending Unit',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 117,
    parts: 'Fuel Tank',
    category: '',
    description:
      'Huge variety of storage from 500 litres to 1,20,000 litres of fuel tankers for fabricating and building a fuel/ diesel tankers in carbon steel stalls in UAE.',
  },
  {
    id: 118,
    parts: 'Fuse Box',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 119,
    parts: 'Glove Box',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 120,
    parts: 'GPS Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 121,
    parts: 'GPS Screen',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 122,
    parts: 'Grille',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 123,
    parts: 'Hard Top',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 124,
    parts: 'Harmonic Balancer (Crank Pulley)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 125,
    parts: 'Hatchback',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 126,
    parts: 'Hatchback Glass',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 127,
    parts: 'Header Panel Assembly',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 128,
    parts: 'Headlight Assembly',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 129,
    parts: 'Headlight Bezel|Door',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 130,
    parts: 'Headlight Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 131,
    parts: 'Headlight Motor',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 132,
    parts: 'Headlight Switch (Auto Headlamps)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 133,
    parts: 'Heads Up Display',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 134,
    parts: 'Heater Controls',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 135,
    parts: 'Heater Core',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 136,
    parts: 'Hood',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 137,
    parts: 'Hood Hinge',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 138,
    parts: 'Hood Piston|Strut',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 139,
    parts: 'Horn',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 140,
    parts: 'Hub',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 141,
    parts: 'Hub Cap (Wheel Cover)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 142,
    parts: 'Ignition Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 143,
    parts: 'Ignition Switch',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 144,
    parts: 'Information Panel',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 145,
    parts: 'Instrument Cluster (Speedometer)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 146,
    parts: 'Intake Manifold',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 147,
    parts: 'Intercooler',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 148,
    parts: 'Jack',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 149,
    parts: 'Keyless Entry Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 150,
    parts: 'Knee Assembly',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 151,
    parts: 'Knuckle (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 152,
    parts: 'Leaf Spring (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 153,
    parts: 'Leaf Spring (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 154,
    parts: 'Lower Control Arm (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 155,
    parts: 'Lower Control Arm (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 156,
    parts: 'Marker Light (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 157,
    parts: 'Marker Light (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 158,
    parts: 'Mass Air Flow Sensor',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 159,
    parts: 'Master Cylinder (Brake)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 160,
    parts: 'Master Cylinder (Clutch)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 161,
    parts: 'Mirror (Rear View)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 162,
    parts: 'Mirror (Side View, Electric)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 163,
    parts: 'Mirror (Side View, Manual)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 164,
    parts: 'Multi-Function Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 165,
    parts: 'Navigation Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 166,
    parts: 'Nose (Front End Assembly)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 167,
    parts: 'Oil Pan (Engine)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 168,
    parts: 'Oil Pan (Transmission)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 169,
    parts: 'Oil Pump',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 170,
    parts: "Owner's Manual",
    category: '',
    description: '',
    img: '',
  },
  {
    id: 171,
    parts: 'Parklight',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 172,
    parts: 'Pickup Bed',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 173,
    parts: 'Pickup Cap|Topper',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 174,
    parts: 'Piston',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 175,
    parts: 'Power Steering Box',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 176,
    parts: 'Power Steering Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 177,
    parts: 'Power Steering Control Valve',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 178,
    parts: 'Power Steering Pump',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 179,
    parts: 'Proportioning Valve (Brake)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 180,
    parts: 'Quarter Glass',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 181,
    parts: 'Quarter Panel Assembly',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 182,
    parts: 'Quarter Window Regulator (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 183,
    parts: 'Radiator',
    category: '',
    description:
      'Well performing radiator at best price in UAE for top tanks, bottom tanks and the core radiator which is the largest part of it.',
  },
  {
    id: 184,
    parts: 'Radiator Cooling Fan',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 185,
    parts: 'Radiator Shroud',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 186,
    parts: 'Radiator Support',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 187,
    parts: 'Radio',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 1881,
    parts: 'Rear Clip',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 189,
    parts: 'Relay (Electrical)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 190,
    parts: 'Reverse Light',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 191,
    parts: 'Rim',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 192,
    parts: 'Ring Gear and Pinion',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 193,
    parts: 'Rocker Panel',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 194,
    parts: 'Roll Bar',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 195,
    parts: 'Roof Assembly',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 196,
    parts: 'Roof Glass',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 197,
    parts: 'Roof Rack',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 198,
    parts: 'Rotor (Brake, Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 199,
    parts: 'Rotor (Brake, Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 200,
    parts: 'Running Board',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 201,
    parts: 'Seat (3rd Row or Bed, Wagon|Van|SUV)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 202,
    parts: 'Seat (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 203,
    parts: 'Seat (Rear or 2nd Row)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 204,
    parts: 'Seat Belt',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 205,
    parts: 'Seat Belt Motor',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 206,
    parts: 'Seat Belt Track',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 207,
    parts: 'Seat Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 208,
    parts: 'Seat Track (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 209,
    parts: 'Security System Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 210,
    parts: 'Shifter Assembly (Floor)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 211,
    parts: 'Shock Absorber',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 212,
    parts: 'Slave Cylinder (Clutch)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 213,
    parts: 'Soft Top',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 214,
    parts: 'Spare Tire (with Rim)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 215,
    parts: 'Spare Tire Carrier',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 216,
    parts: 'Speaker',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 217,
    parts: 'Speedometer Cluster',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 218,
    parts: 'Spindle (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 219,
    parts: 'Spoiler (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 220,
    parts: 'Spoiler (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 221,
    parts: 'Starter',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 222,
    parts: 'Steering Box',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 223,
    parts: 'Steering Column',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 224,
    parts: 'Steering Rack',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 225,
    parts: 'Steering Wheel',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 226,
    parts: 'Strut Assembly (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 227,
    parts: 'Strut Assembly (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 228,
    parts: 'Stub Axle (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 229,
    parts: 'Sun Visor',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 230,
    parts: 'Sunroof Assembly',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 231,
    parts: 'Sunroof Glass',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 232,
    parts: 'Sunroof Motor',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 233,
    parts: 'Supercharger',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 234,
    parts: 'Suspension Assembly (Rear, Independent)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 235,
    parts: 'Suspension Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 236,
    parts: 'Suspension Crossmember (K-Frame)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 237,
    parts: 'Tailgate',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 238,
    parts: 'Tailgate Glass',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 239,
    parts: 'Tailgate Window Regulator',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 240,
    parts: 'Taillight',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 241,
    parts: 'Temperature Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 242,
    parts: 'Temperature Controls',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 243,
    parts: 'Third Brake Light',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 244,
    parts: 'Throttle Body Assembly',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 245,
    parts: 'Timing Cover',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 246,
    parts: 'Tire',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 247,
    parts: 'Torsion Bar',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 248,
    parts: 'Traction Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 249,
    parts: 'Trailer Hitch',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 250,
    parts: 'Trailing Arm',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 251,
    parts: 'Transfer Case Adapter',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 252,
    parts: 'Transfer Case Assembly',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 253,
    parts: 'Transfer Case Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 254,
    parts: 'Transfer Case Shift Motor (Electric Shift)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 255,
    parts: 'Transmission Assembly',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 256,
    parts: 'Transmission Control Module',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 257,
    parts: 'Transmission Torque Converter',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 258,
    parts: 'T-Top',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 259,
    parts: 'Turbocharger',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 260,
    parts: 'Turn Signal Light',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 261,
    parts: 'Upper Control Arm (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 262,
    parts: 'Upper Control Arm (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 263,
    parts: 'Vacuum Pump',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 264,
    parts: 'Valance (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 265,
    parts: 'Valance (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 266,
    parts: 'Valve Cover',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 267,
    parts: 'Voltage Regulator',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 268,
    parts: 'Washer Fluid Reservoir',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 269,
    parts: 'Washer Motor (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 270,
    parts: 'Washer Motor (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 271,
    parts: 'Water Pump',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 272,
    parts: 'Wheel',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 273,
    parts: 'Wheel Cover (Hub Cap)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 274,
    parts: 'Windshield',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 275,
    parts: 'Wiper Arm',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 276,
    parts: 'Wiper Motor (Front)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 277,
    parts: 'Wiper Motor (Rear)',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 278,
    parts: 'Wiper Transmission',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 279,
    parts: 'Brake Pads',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 280,
    parts: 'Bonnet',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 281,
    parts: 'Spark Plug',
    category: '',
    description: '',
    img: '',
  },
  {
    id: 282,
    parts: 'Toe Arms',
    category: '',
    description: '',
    img: '',
  },
];
export default parts;
