export const parts = [
  {
    id: 1,
    parts: "AC Compressor",
    description: "",
    img: "AC_Compressor.png",
  },
  {
    id: 2,
    parts: "AC Condenser",
    description: "",
    img: "AC_Condenser.png",
  },
  {
    id: 3,
    parts: "AC Condenser Cooling Fan",
    description: "",
    img: "AC_Condenser_Cooling_Fan.png",
  },
  {
    id: 4,
    parts: "AC Controls",
    description: "",
    img: "AC_Controls.png",
  },
  {
    id: 5,
    parts: "AC Evaporator",
    description: "",
    img: "",
  },
  {
    id: 6,
    parts: "AC Evaporator Housing",
    description: "",
    img: "",
  },
  {
    id: 7,
    parts: "AC Selector",
    description: "",
    img: "",
  },
  {
    id: 8,
    parts: "Air Bag Assembly",
    description: "",
    img: "",
  },
  {
    id: 9,
    parts: "Air Bag Control Module",
    description: "",
    img: "",
  },
  {
    id: 10,
    parts: "Air Bag Detector",
    description: "",
    img: "",
  },
  {
    id: 11,
    parts: "Air Cleaner Assembly",
    description: "",
    img: "",
  },
  {
    id: 12,
    parts: "Air Flow Meter",
    description: "",
    img: "",
  },
  {
    id: 13,
    parts: "Air Injection Pump",
    description: "",
    img: "",
  },
  {
    id: 14,
    parts: "Air Ride Compressor",
    description: "",
    img: "",
  },
  {
    id: 15,
    parts: "Air Ride Control Module",
    description: "",
    img: "",
  },
  {
    id: 16,
    parts: "Alternator",
    description:
      "Alternators for all vehicles are manufactured using Quality Standards and 100% end-of-line computerised.",
  },
  {
    id: 17,
    parts: "Antenna (Electric)",
    description: "",
    img: "",
  },
  {
    id: 18,
    parts: "Antenna (Manual)",
    description: "",
    img: "",
  },
  {
    id: 19,
    parts: "Anti-Lock Brake Control Module (ABS)",
    description: "",
    img: "",
  },
  {
    id: 20,
    parts: "Anti-Theft Control Module",
    description: "",
    img: "",
  },
  {
    id: 21,
    parts: "Axle Assembly (Front, 4WD)",
    description: "",
    img: "",
  },
  {
    id: 22,
    parts: "Axle Assembly (Rear)",
    description: "",
    img: "",
  },
  {
    id: 23,
    parts: "Axle Beam (Front, 2WD)",
    description: "",
    img: "",
  },
  {
    id: 24,
    parts: "Axle Beam (Rear, FWD, Complete)",
    description: "",
    img: "",
  },
  {
    id: 25,
    parts: "Axle Shaft",
    description: "",
    img: "",
  },
  {
    id: 26,
    parts: "Back Glass",
    description: "",
    img: "",
  },
  {
    id: 27,
    parts: "Backup Light",
    description: "",
    img: "",
  },
  {
    id: 28,
    parts: "Battery",
    description:
      "The Automobile Batteries are manufactured using the best quality raw materials that has a high power, performance and reliability.",
  },
  {
    id: 29,
    parts: "Bed (Pickup)",
    description: "",
    img: "",
  },
  {
    id: 30,
    parts: "Bell Housing",
    description: "",
    img: "",
  },
  {
    id: 31,
    parts: "Belt Tensioner",
    description: "",
    img: "",
  },
  {
    id: 32,
    parts: "Blower Motor",
    description: "",
    img: "",
  },
  {
    id: 33,
    parts: "Body Control Module (BCM)",
    description: "",
    img: "",
  },
  {
    id: 34,
    parts: "Brake Booster",
    description:
      "Braking system from high end manufacturers using high quality metallic, carbon-based, brass bonded resins, steel and graphite in UAE.",
  },
  {
    id: 35,
    parts: "Bumper Assembly (Front)",
    description: "",
    img: "",
  },
  {
    id: 36,
    parts: "Bumper Assembly (Rear)",
    description: "",
    img: "",
  },
  {
    id: 37,
    parts: "Bumper Cover (Front)",
    description: "",
    img: "",
  },
  {
    id: 38,
    parts: "Bumper Cover (Rear)",
    description: "",
    img: "",
  },
  {
    id: 39,
    parts: "Bumper Shock",
    description: "",
    img: "",
  },
  {
    id: 40,
    parts: "Cab Clip",
    description: "",
    img: "",
  },
  {
    id: 41,
    parts: "Caliper",
    description: "",
    img: "",
  },
  {
    id: 42,
    parts: "Camshaft",
    description: "",
    img: "",
  },
  {
    id: 43,
    parts: "Carburetor",
    description: "",
    img: "",
  },
  {
    id: 44,
    parts: "Carrier Assembly",
    description: "",
    img: "",
  },
  {
    id: 45,
    parts: "Cassette Player",
    description: "",
    img: "",
  },
  {
    id: 46,
    parts: "CD Changer",
    description: "",
    img: "",
  },
  {
    id: 47,
    parts: "CD Player",
    description: "",
    img: "",
  },
  {
    id: 48,
    parts: "Chassis Control Module",
    description: "",
    img: "",
  },
  {
    id: 49,
    parts: "Clock",
    description: "",
    img: "",
  },
  {
    id: 50,
    parts: "Coil (Ignition)",
    description: "",
    img: "",
  },
  {
    id: 51,
    parts: "Coil Spring (Front)",
    description: "",
    img: "",
  },
  {
    id: 52,
    parts: "Coil Spring (Rear)",
    description: "",
    img: "",
  },
  {
    id: 53,
    parts: "Column Shift Lever",
    description: "",
    img: "",
  },
  {
    id: 54,
    parts: "Column Switch",
    description: "",
    img: "",
  },
  {
    id: 55,
    parts: "Computer (ECU, ECM)",
    description: "",
    img: "",
  },
  {
    id: 56,
    parts: "Console",
    description: "",
    img: "",
  },
  {
    id: 57,
    parts: "Control Module",
    description: "",
    img: "",
  },
  {
    id: 58,
    parts: "Convertible Top",
    description: "",
    img: "",
  },
  {
    id: 59,
    parts: "Convertible Top Motor",
    description: "",
    img: "",
  },
  {
    id: 60,
    parts: "Coolant Reservoir",
    description: "",
    img: "",
  },
  {
    id: 61,
    parts: "Cooling Fans Assembly (Rad. & Cond.)",
    description: "",
    img: "",
  },
  {
    id: 62,
    parts: "Cornering Light",
    description: "",
    img: "",
  },
  {
    id: 63,
    parts: "Cowl",
    description: "",
    img: "",
  },
  {
    id: 64,
    parts: "Crankshaft",
    description: "",
    img: "",
  },
  {
    id: 65,
    parts: "Cruise Control Module",
    description: "",
    img: "",
  },
  {
    id: 66,
    parts: "Cylinder Block",
    description: "",
    img: "",
  },
  {
    id: 67,
    parts: "Cylinder Head",
    description: "",
    img: "",
  },
  {
    id: 68,
    parts: "Dashboard Assembly",
    description: "",
    img: "",
  },
  {
    id: 69,
    parts: "Dashboard Pad",
    description: "",
    img: "",
  },
  {
    id: 70,
    parts: "Decklid",
    description: "",
    img: "",
  },
  {
    id: 71,
    parts: "Decklid Pull Down Motor",
    description: "",
    img: "",
  },
  {
    id: 72,
    parts: "Differential Assembly (Front)",
    description: "",
    img: "",
  },
  {
    id: 73,
    parts: "Differential Assembly (Rear)",
    description: "",
    img: "",
  },
  {
    id: 74,
    parts: "Differential Case",
    description: "",
    img: "",
  },
  {
    id: 75,
    parts: "Distributor",
    description: "",
    img: "",
  },
  {
    id: 76,
    parts: "Door Assembly (Front)",
    description: "",
    img: "",
  },
  {
    id: 77,
    parts: "Door Assembly (Rear or Back)",
    description: "",
    img: "",
  },
  {
    id: 78,
    parts: "Door Glass (Front)",
    description: "",
    img: "",
  },
  {
    id: 79,
    parts: "Door Glass (Rear)",
    description: "",
    img: "",
  },
  {
    id: 80,
    parts: "Door Handle (Inside)",
    description: "",
    img: "",
  },
  {
    id: 81,
    parts: "Door Handle (Outside)",
    description: "",
    img: "",
  },
  {
    id: 82,
    parts: "Door Lock Control Module",
    description: "",
    img: "",
  },
  {
    id: 83,
    parts: "Door Motor (Power Slider|Tailgate, Van)",
    description: "",
    img: "",
  },
  {
    id: 84,
    parts: "Door Switch",
    description: "",
    img: "",
  },
  {
    id: 85,
    parts: "Door Vent Glass (Front)",
    description: "",
    img: "",
  },
  {
    id: 86,
    parts: "Door Vent Glass (Rear)",
    description: "",
    img: "",
  },
  {
    id: 87,
    parts: "Door Vent Glass Regulator (Front)",
    description: "",
    img: "",
  },
  {
    id: 88,
    parts: "Door Window Control Module",
    description: "",
    img: "",
  },
  {
    id: 89,
    parts: "Door Window Motor (Front)",
    description: "",
    img: "",
  },
  {
    id: 90,
    parts: "Door Window Motor (Rear)",
    description: "",
    img: "",
  },
  {
    id: 91,
    parts: "Door Window Regulator (Front)",
    description: "",
    img: "",
  },
  {
    id: 92,
    parts: "Door Window Regulator (Rear)",
    description: "",
    img: "",
  },
  {
    id: 93,
    parts: "Drive Shaft (Front)",
    description: "",
    img: "",
  },
  {
    id: 94,
    parts: "Drive Shaft (Rear)",
    description: "",
    img: "",
  },
  {
    id: 95,
    parts: "Driving Light",
    description: "",
    img: "",
  },
  {
    id: 96,
    parts: "Engine Assembly",
    description: "",
    img: "",
  },
  {
    id: 97,
    parts: "Engine Block",
    description: "",
    img: "",
  },
  {
    id: 98,
    parts: "Engine Control Module (ECU, ECM)",
    description: "",
    img: "",
  },
  {
    id: 99,
    parts: "Engine Mount",
    description: "",
    img: "",
  },
  {
    id: 100,
    parts: "Engine Oil Cooler",
    description: "",
    img: "",
  },
  {
    id: 101,
    parts: "Engine Wiring Harness",
    description: "",
    img: "",
  },
  {
    id: 102,
    parts: "Exhaust Manifold",
    description: "",
    img: "",
  },
  {
    id: 103,
    parts: "Fan Blade",
    description: "",
    img: "",
  },
  {
    id: 104,
    parts: "Fan Clutch",
    description: "",
    img: "",
  },
  {
    id: 105,
    parts: "Fan Control Module",
    description: "",
    img: "",
  },
  {
    id: 106,
    parts: "Fender (Front)",
    description: "",
    img: "",
  },
  {
    id: 107,
    parts: "Fender (Rear)",
    description: "",
    img: "",
  },
  {
    id: 108,
    parts: "Flywheel",
    description: "",
    img: "",
  },
  {
    id: 109,
    parts: "Fog Light",
    description: "",
    img: "",
  },
  {
    id: 110,
    parts: "Frame (Complete)",
    description: "",
    img: "",
  },
  {
    id: 111,
    parts: "Frame (Front)",
    description: "",
    img: "",
  },
  {
    id: 112,
    parts: "Front End Assembly (Nose)",
    description: "",
    img: "",
  },
  {
    id: 113,
    parts: "Fuel Door",
    description: "",
    img: "",
  },
  {
    id: 114,
    parts: "Fuel Injection Pump",
    description: "",
    img: "",
  },
  {
    id: 115,
    parts: "Fuel Pump",
    description: "",
    img: "",
  },
  {
    id: 116,
    parts: "Fuel Sending Unit",
    description: "",
    img: "",
  },
  {
    id: 117,
    parts: "Fuel Tank",
    description:
      "Huge variety of storage from 500 litres to 1,20,000 litres of fuel tankers for fabricating and building a fuel/ diesel tankers in carbon steel stalls in UAE.",
  },
  {
    id: 118,
    parts: "Fuse Box",
    description: "",
    img: "",
  },
  {
    id: 119,
    parts: "Glove Box",
    description: "",
    img: "",
  },
  {
    id: 120,
    parts: "GPS Control Module",
    description: "",
    img: "",
  },
  {
    id: 121,
    parts: "GPS Screen",
    description: "",
    img: "",
  },
  {
    id: 122,
    parts: "Grille",
    description: "",
    img: "",
  },
  {
    id: 123,
    parts: "Hard Top",
    description: "",
    img: "",
  },
  {
    id: 124,
    parts: "Harmonic Balancer (Crank Pulley)",
    description: "",
    img: "",
  },
  {
    id: 125,
    parts: "Hatchback",
    description: "",
    img: "",
  },
  {
    id: 126,
    parts: "Hatchback Glass",
    description: "",
    img: "",
  },
  {
    id: 127,
    parts: "Header Panel Assembly",
    description: "",
    img: "",
  },
  {
    id: 128,
    parts: "Headlight Assembly",
    description: "",
    img: "",
  },
  {
    id: 129,
    parts: "Headlight Bezel|Door",
    description: "",
    img: "",
  },
  {
    id: 130,
    parts: "Headlight Control Module",
    description: "",
    img: "",
  },
  {
    id: 131,
    parts: "Headlight Motor",
    description: "",
    img: "",
  },
  {
    id: 132,
    parts: "Headlight Switch (Auto Headlamps)",
    description: "",
    img: "",
  },
  {
    id: 133,
    parts: "Heads Up Display",
    description: "",
    img: "",
  },
  {
    id: 134,
    parts: "Heater Controls",
    description: "",
    img: "",
  },
  {
    id: 135,
    parts: "Heater Core",
    description: "",
    img: "",
  },
  {
    id: 136,
    parts: "Hood",
    description: "",
    img: "",
  },
  {
    id: 137,
    parts: "Hood Hinge",
    description: "",
    img: "",
  },
  {
    id: 138,
    parts: "Hood Piston|Strut",
    description: "",
    img: "",
  },
  {
    id: 139,
    parts: "Horn",
    description: "",
    img: "",
  },
  {
    id: 140,
    parts: "Hub",
    description: "",
    img: "",
  },
  {
    id: 141,
    parts: "Hub Cap (Wheel Cover)",
    description: "",
    img: "",
  },
  {
    id: 142,
    parts: "Ignition Control Module",
    description: "",
    img: "",
  },
  {
    id: 143,
    parts: "Ignition Switch",
    description: "",
    img: "",
  },
  {
    id: 144,
    parts: "Information Panel",
    description: "",
    img: "",
  },
  {
    id: 145,
    parts: "Instrument Cluster (Speedometer)",
    description: "",
    img: "",
  },
  {
    id: 146,
    parts: "Intake Manifold",
    description: "",
    img: "",
  },
  {
    id: 147,
    parts: "Intercooler",
    description: "",
    img: "",
  },
  {
    id: 148,
    parts: "Jack",
    description: "",
    img: "",
  },
  {
    id: 149,
    parts: "Keyless Entry Control Module",
    description: "",
    img: "",
  },
  {
    id: 150,
    parts: "Knee Assembly",
    description: "",
    img: "",
  },
  {
    id: 151,
    parts: "Knuckle (Front)",
    description: "",
    img: "",
  },
  {
    id: 152,
    parts: "Leaf Spring (Front)",
    description: "",
    img: "",
  },
  {
    id: 153,
    parts: "Leaf Spring (Rear)",
    description: "",
    img: "",
  },
  {
    id: 154,
    parts: "Lower Control Arm (Front)",
    description: "",
    img: "",
  },
  {
    id: 155,
    parts: "Lower Control Arm (Rear)",
    description: "",
    img: "",
  },
  {
    id: 156,
    parts: "Marker Light (Front)",
    description: "",
    img: "",
  },
  {
    id: 157,
    parts: "Marker Light (Rear)",
    description: "",
    img: "",
  },
  {
    id: 158,
    parts: "Mass Air Flow Sensor",
    description: "",
    img: "",
  },
  {
    id: 159,
    parts: "Master Cylinder (Brake)",
    description: "",
    img: "",
  },
  {
    id: 160,
    parts: "Master Cylinder (Clutch)",
    description: "",
    img: "",
  },
  {
    id: 161,
    parts: "Mirror (Rear View)",
    description: "",
    img: "",
  },
  {
    id: 162,
    parts: "Mirror (Side View, Electric)",
    description: "",
    img: "",
  },
  {
    id: 163,
    parts: "Mirror (Side View, Manual)",
    description: "",
    img: "",
  },
  {
    id: 164,
    parts: "Multi-Function Control Module",
    description: "",
    img: "",
  },
  {
    id: 165,
    parts: "Navigation Control Module",
    description: "",
    img: "",
  },
  {
    id: 166,
    parts: "Nose (Front End Assembly)",
    description: "",
    img: "",
  },
  {
    id: 167,
    parts: "Oil Pan (Engine)",
    description: "",
    img: "",
  },
  {
    id: 168,
    parts: "Oil Pan (Transmission)",
    description: "",
    img: "",
  },
  {
    id: 169,
    parts: "Oil Pump",
    description: "",
    img: "",
  },
  {
    id: 170,
    parts: "Owner's Manual",
    description: "",
    img: "",
  },
  {
    id: 171,
    parts: "Parklight",
    description: "",
    img: "",
  },
  {
    id: 172,
    parts: "Pickup Bed",
    description: "",
    img: "",
  },
  {
    id: 173,
    parts: "Pickup Cap|Topper",
    description: "",
    img: "",
  },
  {
    id: 174,
    parts: "Piston",
    description: "",
    img: "",
  },
  {
    id: 175,
    parts: "Power Steering Box",
    description: "",
    img: "",
  },
  {
    id: 176,
    parts: "Power Steering Control Module",
    description: "",
    img: "",
  },
  {
    id: 177,
    parts: "Power Steering Control Valve",
    description: "",
    img: "",
  },
  {
    id: 178,
    parts: "Power Steering Pump",
    description: "",
    img: "",
  },
  {
    id: 179,
    parts: "Proportioning Valve (Brake)",
    description: "",
    img: "",
  },
  {
    id: 180,
    parts: "Quarter Glass",
    description: "",
    img: "",
  },
  {
    id: 181,
    parts: "Quarter Panel Assembly",
    description: "",
    img: "",
  },
  {
    id: 182,
    parts: "Quarter Window Regulator (Rear)",
    description: "",
    img: "",
  },
  {
    id: 183,
    parts: "Radiator",
    description:
      "Well performing radiator at best price in UAE for top tanks, bottom tanks and the core radiator which is the largest part of it.",
  },
  {
    id: 184,
    parts: "Radiator Cooling Fan",
    description: "",
    img: "",
  },
  {
    id: 185,
    parts: "Radiator Shroud",
    description: "",
    img: "",
  },
  {
    id: 186,
    parts: "Radiator Support",
    description: "",
    img: "",
  },
  {
    id: 187,
    parts: "Radio",
    description: "",
    img: "",
  },
  {
    id: 188,
    parts: "Rear Clip",
    description: "",
    img: "",
  },
  {
    id: 189,
    parts: "Relay (Electrical)",
    description: "",
    img: "",
  },
  {
    id: 190,
    parts: "Reverse Light",
    description: "",
    img: "",
  },
  {
    id: 191,
    parts: "Rim",
    description: "",
    img: "",
  },
  {
    id: 192,
    parts: "Ring Gear and Pinion",
    description: "",
    img: "",
  },
  {
    id: 193,
    parts: "Rocker Panel",
    description: "",
    img: "",
  },
  {
    id: 194,
    parts: "Roll Bar",
    description: "",
    img: "",
  },
  {
    id: 195,
    parts: "Roof Assembly",
    description: "",
    img: "",
  },
  {
    id: 196,
    parts: "Roof Glass",
    description: "",
    img: "",
  },
  {
    id: 197,
    parts: "Roof Rack",
    description: "",
    img: "",
  },
  {
    id: 198,
    parts: "Rotor (Brake, Front)",
    description: "",
    img: "",
  },
  {
    id: 199,
    parts: "Rotor (Brake, Rear)",
    description: "",
    img: "",
  },
  {
    id: 200,
    parts: "Running Board",
    description: "",
    img: "",
  },
  {
    id: 201,
    parts: "Seat (3rd Row or Bed, Wagon|Van|SUV)",
    description: "",
    img: "",
  },
  {
    id: 202,
    parts: "Seat (Front)",
    description: "",
    img: "",
  },
  {
    id: 203,
    parts: "Seat (Rear or 2nd Row)",
    description: "",
    img: "",
  },
  {
    id: 204,
    parts: "Seat Belt",
    description: "",
    img: "",
  },
  {
    id: 205,
    parts: "Seat Belt Motor",
    description: "",
    img: "",
  },
  {
    id: 206,
    parts: "Seat Belt Track",
    description: "",
    img: "",
  },
  {
    id: 207,
    parts: "Seat Control Module",
    description: "",
    img: "",
  },
  {
    id: 208,
    parts: "Seat Track (Front)",
    description: "",
    img: "",
  },
  {
    id: 209,
    parts: "Security System Control Module",
    description: "",
    img: "",
  },
  {
    id: 210,
    parts: "Shifter Assembly (Floor)",
    description: "",
    img: "",
  },
  {
    id: 211,
    parts: "Shock Absorber",
    description: "",
    img: "",
  },
  {
    id: 212,
    parts: "Slave Cylinder (Clutch)",
    description: "",
    img: "",
  },
  {
    id: 213,
    parts: "Soft Top",
    description: "",
    img: "",
  },
  {
    id: 214,
    parts: "Spare Tire (with Rim)",
    description: "",
    img: "",
  },
  {
    id: 215,
    parts: "Spare Tire Carrier",
    description: "",
    img: "",
  },
  {
    id: 216,
    parts: "Speaker",
    description: "",
    img: "",
  },
  {
    id: 217,
    parts: "Speedometer Cluster",
    description: "",
    img: "",
  },
  {
    id: 218,
    parts: "Spindle (Front)",
    description: "",
    img: "",
  },
  {
    id: 219,
    parts: "Spoiler (Front)",
    description: "",
    img: "",
  },
  {
    id: 220,
    parts: "Spoiler (Rear)",
    description: "",
    img: "",
  },
  {
    id: 221,
    parts: "Starter",
    description: "",
    img: "",
  },
  {
    id: 222,
    parts: "Steering Box",
    description: "",
    img: "",
  },
  {
    id: 223,
    parts: "Steering Column",
    description: "",
    img: "",
  },
  {
    id: 224,
    parts: "Steering Rack",
    description: "",
    img: "",
  },
  {
    id: 225,
    parts: "Steering Wheel",
    description: "",
    img: "",
  },
  {
    id: 226,
    parts: "Strut Assembly (Front)",
    description: "",
    img: "",
  },
  {
    id: 227,
    parts: "Strut Assembly (Rear)",
    description: "",
    img: "",
  },
  {
    id: 228,
    parts: "Stub Axle (Rear)",
    description: "",
    img: "",
  },
  {
    id: 229,
    parts: "Sun Visor",
    description: "",
    img: "",
  },
  {
    id: 230,
    parts: "Sunroof Assembly",
    description: "",
    img: "",
  },
  {
    id: 231,
    parts: "Sunroof Glass",
    description: "",
    img: "",
  },
  {
    id: 232,
    parts: "Sunroof Motor",
    description: "",
    img: "",
  },
  {
    id: 233,
    parts: "Supercharger",
    description: "",
    img: "",
  },
  {
    id: 234,
    parts: "Suspension Assembly (Rear, Independent)",
    description: "",
    img: "",
  },
  {
    id: 235,
    parts: "Suspension Control Module",
    description: "",
    img: "",
  },
  {
    id: 236,
    parts: "Suspension Crossmember (K-Frame)",
    description: "",
    img: "",
  },
  {
    id: 237,
    parts: "Tailgate",
    description: "",
    img: "",
  },
  {
    id: 238,
    parts: "Tailgate Glass",
    description: "",
    img: "",
  },
  {
    id: 239,
    parts: "Tailgate Window Regulator",
    description: "",
    img: "",
  },
  {
    id: 240,
    parts: "Taillight",
    description: "",
    img: "",
  },
  {
    id: 241,
    parts: "Temperature Control Module",
    description: "",
    img: "",
  },
  {
    id: 242,
    parts: "Temperature Controls",
    description: "",
    img: "",
  },
  {
    id: 243,
    parts: "Third Brake Light",
    description: "",
    img: "",
  },
  {
    id: 244,
    parts: "Throttle Body Assembly",
    description: "",
    img: "",
  },
  {
    id: 245,
    parts: "Timing Cover",
    description: "",
    img: "",
  },
  {
    id: 246,
    parts: "Tire",
    description: "",
    img: "",
  },
  {
    id: 247,
    parts: "Torsion Bar",
    description: "",
    img: "",
  },
  {
    id: 248,
    parts: "Traction Control Module",
    description: "",
    img: "",
  },
  {
    id: 249,
    parts: "Trailer Hitch",
    description: "",
    img: "",
  },
  {
    id: 250,
    parts: "Trailing Arm",
    description: "",
    img: "",
  },
  {
    id: 251,
    parts: "Transfer Case Adapter",
    description: "",
    img: "",
  },
  {
    id: 252,
    parts: "Transfer Case Assembly",
    description: "",
    img: "",
  },
  {
    id: 253,
    parts: "Transfer Case Control Module",
    description: "",
    img: "",
  },
  {
    id: 254,
    parts: "Transfer Case Shift Motor (Electric Shift)",
    description: "",
    img: "",
  },
  {
    id: 255,
    parts: "Transmission Assembly",
    description: "",
    img: "",
  },
  {
    id: 256,
    parts: "Transmission Control Module",
    description: "",
    img: "",
  },
  {
    id: 257,
    parts: "Transmission Torque Converter",
    description: "",
    img: "",
  },
  {
    id: 258,
    parts: "T-Top",
    description: "",
    img: "",
  },
  {
    id: 259,
    parts: "Turbocharger",
    description: "",
    img: "",
  },
  {
    id: 260,
    parts: "Turn Signal Light",
    description: "",
    img: "",
  },
  {
    id: 261,
    parts: "Upper Control Arm (Front)",
    description: "",
    img: "",
  },
  {
    id: 262,
    parts: "Upper Control Arm (Rear)",
    description: "",
    img: "",
  },
  {
    id: 263,
    parts: "Vacuum Pump",
    description: "",
    img: "",
  },
  {
    id: 264,
    parts: "Valance (Front)",
    description: "",
    img: "",
  },
  {
    id: 265,
    parts: "Valance (Rear)",
    description: "",
    img: "",
  },
  {
    id: 266,
    parts: "Valve Cover",
    description: "",
    img: "",
  },
  {
    id: 267,
    parts: "Voltage Regulator",
    description: "",
    img: "",
  },
  {
    id: 268,
    parts: "Washer Fluid Reservoir",
    description: "",
    img: "",
  },
  {
    id: 269,
    parts: "Washer Motor (Front)",
    description: "",
    img: "",
  },
  {
    id: 270,
    parts: "Washer Motor (Rear)",
    description: "",
    img: "",
  },
  {
    id: 271,
    parts: "Water Pump",
    description: "",
    img: "",
  },
  {
    id: 272,
    parts: "Wheel",
    description: "",
    img: "",
  },
  {
    id: 273,
    parts: "Wheel Cover (Hub Cap)",
    description: "",
    img: "",
  },
  {
    id: 274,
    parts: "Windshield",
    description: "",
    img: "",
  },
  {
    id: 275,
    parts: "Wiper Arm",
    description: "",
    img: "",
  },
  {
    id: 276,
    parts: "Wiper Motor (Front)",
    description: "",
    img: "",
  },
  {
    id: 277,
    parts: "Wiper Motor (Rear)",
    description: "",
    img: "",
  },
  {
    id: 278,
    parts: "Wiper Transmission",
    description: "",
    img: "",
  },
];
export default parts;
